CREATE DATABASE MANAGEMENT_BOOKSTORE_ONLINE
GO

USE MANAGEMENT_BOOKSTORE_ONLINE
GO

CREATE TABLE ROLES
(
	ID_ROLE INT PRIMARY KEY,
	ROLE_NAME NVARCHAR(30),
	CONSTRAINT CH_IDROLE CHECK (ID_ROLE >= 0 AND ID_ROLE <=2)
);

INSERT INTO ROLES(ID_ROLE, ROLE_NAME) VALUES (0, 'ADMIN')
INSERT INTO ROLES(ID_ROLE, ROLE_NAME) VALUES (1, 'STAFF')
INSERT INTO ROLES(ID_ROLE, ROLE_NAME) VALUES (2, 'CUSTOMER')


CREATE TABLE USERS(
	ID_USER INT IDENTITY PRIMARY KEY, 
	ID_ROLE INT NULL, --ID NÀY ĐỂ FK ĐẾN ROLES
	USER_NAME NVARCHAR(35), 
	USER_AGE INT, 
	USER_ADDRESS NVARCHAR(200),
	USER_PHONE NCHAR(11),
	USER_EMAIL NCHAR(50)
	CONSTRAINT FK_USERS_ROLES FOREIGN KEY(ID_ROLE) REFERENCES ROLES(ID_ROLE)
);

INSERT INTO USERS(ID_ROLE, USER_NAME, USER_AGE, USER_ADDRESS, USER_PHONE, USER_EMAIL) 
VALUES (2,'Nguyen Linh Nhi', 20, N'Kien Giang', '-', 'nln@gmail.com')

--Table USER này để lưu thông tin tài khoản login
CREATE TABLE ACCOUNTS
(
	ID INT IDENTITY PRIMARY KEY, 
	ID_USER INT NULL,
	USERNAME NVARCHAR(30) NOT NULL, 
	HashPassword NCHAR(20) NOT NULL, 
	STATUS BIT NOT NULL DEFAULT 1
);

/*
ALTER TABLE USERS
ADD ID_ROLE INT 

ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID_ROLE);
*/

INSERT INTO ACCOUNTS(USERNAME, HashPassword,ID_USER) VALUES ('admin','123',NULL)
INSERT INTO ACCOUNTS(USERNAME, HashPassword,ID_USER) VALUES ('customer','123',1)
INSERT INTO ACCOUNTS(USERNAME, HashPassword,ID_USER) VALUES ('staff','123',NULL)


SELECT * FROM ROLES;
SELECT * FROM USERS;
SELECT * FROM ACCOUNTS;



SELECT U.USER_NAME, A.USERNAME, A.HashPassword, R.ROLE_NAME
FROM ROLES R, USERS U, ACCOUNTS A
WHERE R.ID_ROLE = U.ID_ROLE AND A.ID_USER = U.ID_USER




DROP TABLE STAFFS;
DROP TABLE CUSTOMERS;
DROP TABLE USERS;